// Code generated by goctl. DO NOT EDIT.
package types

type SignUpRequest struct {
	AuthType int    `form:"authType"`
	Token    string `form:"token"`
	Email    string `form:"email"`
	Password string `form:"password"`
}

type LoginRequest struct {
	AuthType int    `form:"authType"`
	Token    string `form:"token"`
	Email    string `form:"email"`
	Password string `form:"password"`
}

type SignUpResponse struct {
	AccessToken  string      `json:"accessToken"`
	RefreshToken string      `json:"refreshToken"`
	UserInfo     interface{} `json:"userInfo"`
}

type LoginResponse struct {
	AccessToken  string      `json:"accessToken"`
	RefreshToken string      `json:"refreshToken"`
	UserInfo     interface{} `json:"userInfo"`
}

type BasicInfo struct {
	Name             string            `json:"name"`
	ResidingLocation string            `json:"residing_location"`
	Tags             []string          `json:"tag"`
	MatchingScore    int8              `json:"matching_score"`
	Personality      string            `json:"personality"`
	EducationHistory []Education       `json:"education_history"`
	WorkHistory      []Work            `json:"work_history"`
	OtherExperience  []OtherExperience `json:"other_experience"`
}

type Education struct {
	Level       int8   `json:"level"`
	Provider    string `json:"provider"`
	Discription string `json:"discription"`
	Gpa         string `json:"gpa"`
}

type Work struct {
	CompanyName string `json:"company_name"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type OtherExperience struct {
	Description string `json:"description"`
}

type Request struct {
	Id string `form:"id"`
}

type Response struct {
	BasicInfo
}
